name: "Set Label"
on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["lgtm", "approve"]'
          labels: '["lgtm"]'
          github-token: "${{ secrets.CHILLY_BOT_TOKEN }}"
