name: Codecov
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.7'
    steps:
      - uses: actions/checkout@master
      - name: Generate coverage report
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
